### ISSUE TITLE
NServiceBus.NLog doesn't support NLog 5.0.0 

### ISSUE THREAD

**Issue by MikhailIvanou** [Particular/NServiceBus.NLog#213]
NLog 5.0.0 has been released recently, but currently restrictions on NLog nuget package is [4.5.3, 5.0.0) 
Are there any plans to support the newest one?

**Comment by snakefoot** [comment]
Notice that NLog 5.0 only includes very few breaking changes in the API.

Unless using old methods already marked obsolete, then libraries will work fine with NLog v4 and NLog v5 without issues.

Suggest that version range is bumped to `[4.5.3, 6.0.0)`

**Comment by snakefoot** [comment]
But after #67 then I guess this issue can be closed
